// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Room struct {
	ID                 pgtype.UUID        `json:"id"`
	Slug               string             `json:"slug"`
	DisplayName        string             `json:"display_name"`
	Description        pgtype.Text        `json:"description"`
	Tags               []string           `json:"tags"`
	IsPrivate          bool               `json:"is_private"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	AnonymousSessionID pgtype.Text        `json:"anonymous_session_id"`
	TokenHash          string             `json:"token_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastActiveAt       pgtype.Timestamptz `json:"last_active_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Provider    string             `json:"provider"`
	ProviderID  string             `json:"provider_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
