// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAgentPresence = `-- name: UpsertAgentPresence :one
INSERT INTO agent_presence (room_id, agent_name, card_json, ttl_seconds)
VALUES ($1, $2, $3, $4)
ON CONFLICT (room_id, agent_name)
DO UPDATE SET card_json = EXCLUDED.card_json, last_seen = NOW(), ttl_seconds = EXCLUDED.ttl_seconds
RETURNING id, room_id, agent_name, card_json, joined_at, last_seen, ttl_seconds
`

type UpsertAgentPresenceParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	AgentName  string      `json:"agent_name"`
	CardJson   []byte      `json:"card_json"`
	TtlSeconds int32       `json:"ttl_seconds"`
}

func (q *Queries) UpsertAgentPresence(ctx context.Context, arg UpsertAgentPresenceParams) (AgentPresence, error) {
	row := q.db.QueryRow(ctx, upsertAgentPresence, arg.RoomID, arg.AgentName, arg.CardJson, arg.TtlSeconds)
	var i AgentPresence
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentName,
		&i.CardJson,
		&i.JoinedAt,
		&i.LastSeen,
		&i.TtlSeconds,
	)
	return i, err
}

const removeAgentPresence = `-- name: RemoveAgentPresence :exec
DELETE FROM agent_presence WHERE room_id = $1 AND agent_name = $2
`

type RemoveAgentPresenceParams struct {
	RoomID    pgtype.UUID `json:"room_id"`
	AgentName string      `json:"agent_name"`
}

func (q *Queries) RemoveAgentPresence(ctx context.Context, arg RemoveAgentPresenceParams) error {
	_, err := q.db.Exec(ctx, removeAgentPresence, arg.RoomID, arg.AgentName)
	return err
}

const listAgentPresenceByRoom = `-- name: ListAgentPresenceByRoom :many
SELECT id, room_id, agent_name, card_json, joined_at, last_seen, ttl_seconds FROM agent_presence
WHERE room_id = $1 AND last_seen > NOW() - (ttl_seconds || ' seconds')::interval
ORDER BY joined_at
`

func (q *Queries) ListAgentPresenceByRoom(ctx context.Context, roomID pgtype.UUID) ([]AgentPresence, error) {
	rows, err := q.db.Query(ctx, listAgentPresenceByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentPresence
	for rows.Next() {
		var i AgentPresence
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AgentName,
			&i.CardJson,
			&i.JoinedAt,
			&i.LastSeen,
			&i.TtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentHeartbeat = `-- name: UpdateAgentHeartbeat :exec
UPDATE agent_presence SET last_seen = NOW() WHERE room_id = $1 AND agent_name = $2
`

type UpdateAgentHeartbeatParams struct {
	RoomID    pgtype.UUID `json:"room_id"`
	AgentName string      `json:"agent_name"`
}

func (q *Queries) UpdateAgentHeartbeat(ctx context.Context, arg UpdateAgentHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateAgentHeartbeat, arg.RoomID, arg.AgentName)
	return err
}

const deleteExpiredAgentPresence = `-- name: DeleteExpiredAgentPresence :many
DELETE FROM agent_presence
WHERE last_seen < NOW() - (ttl_seconds || ' seconds')::interval
RETURNING room_id, agent_name
`

type DeleteExpiredAgentPresenceRow struct {
	RoomID    pgtype.UUID `json:"room_id"`
	AgentName string      `json:"agent_name"`
}

func (q *Queries) DeleteExpiredAgentPresence(ctx context.Context) ([]DeleteExpiredAgentPresenceRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredAgentPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteExpiredAgentPresenceRow
	for rows.Next() {
		var i DeleteExpiredAgentPresenceRow
		if err := rows.Scan(&i.RoomID, &i.AgentName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPublicAgentPresence = `-- name: ListAllPublicAgentPresence :many
SELECT ap.id, ap.room_id, ap.agent_name, ap.card_json, ap.joined_at, ap.last_seen, ap.ttl_seconds FROM agent_presence ap
JOIN rooms r ON r.id = ap.room_id
WHERE r.is_private = FALSE
AND ap.last_seen > NOW() - (ap.ttl_seconds || ' seconds')::interval
ORDER BY ap.last_seen DESC
`

func (q *Queries) ListAllPublicAgentPresence(ctx context.Context) ([]AgentPresence, error) {
	rows, err := q.db.Query(ctx, listAllPublicAgentPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentPresence
	for rows.Next() {
		var i AgentPresence
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AgentName,
			&i.CardJson,
			&i.JoinedAt,
			&i.LastSeen,
			&i.TtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomLastActive = `-- name: UpdateRoomLastActive :exec
UPDATE rooms SET last_active_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateRoomLastActive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateRoomLastActive, id)
	return err
}

const claimAnonymousRooms = `-- name: ClaimAnonymousRooms :exec
UPDATE rooms SET owner_id = $1, anonymous_session_id = NULL, expires_at = NULL
WHERE anonymous_session_id = $2 AND owner_id IS NULL
`

type ClaimAnonymousRoomsParams struct {
	OwnerID            pgtype.UUID `json:"owner_id"`
	AnonymousSessionID pgtype.Text `json:"anonymous_session_id"`
}

func (q *Queries) ClaimAnonymousRooms(ctx context.Context, arg ClaimAnonymousRoomsParams) error {
	_, err := q.db.Exec(ctx, claimAnonymousRooms, arg.OwnerID, arg.AnonymousSessionID)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at
`

type CreateRoomParams struct {
	Slug               string             `json:"slug"`
	DisplayName        string             `json:"display_name"`
	Description        pgtype.Text        `json:"description"`
	Tags               []string           `json:"tags"`
	IsPrivate          bool               `json:"is_private"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	AnonymousSessionID pgtype.Text        `json:"anonymous_session_id"`
	TokenHash          string             `json:"token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
		arg.IsPrivate,
		arg.OwnerID,
		arg.AnonymousSessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.IsPrivate,
		&i.OwnerID,
		&i.AnonymousSessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteExpiredRooms = `-- name: DeleteExpiredRooms :exec
DELETE FROM rooms WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredRooms(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRooms)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at FROM refresh_tokens WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.IsPrivate,
		&i.OwnerID,
		&i.AnonymousSessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRoomBySlug = `-- name: GetRoomBySlug :one
SELECT id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at FROM rooms WHERE slug = $1
`

func (q *Queries) GetRoomBySlug(ctx context.Context, slug string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomBySlug, slug)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.IsPrivate,
		&i.OwnerID,
		&i.AnonymousSessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRoomByTokenHash = `-- name: GetRoomByTokenHash :one
SELECT id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at FROM rooms WHERE token_hash = $1
`

func (q *Queries) GetRoomByTokenHash(ctx context.Context, tokenHash string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByTokenHash, tokenHash)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.IsPrivate,
		&i.OwnerID,
		&i.AnonymousSessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, provider, provider_id, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, provider, provider_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicRooms = `-- name: ListPublicRooms :many
SELECT id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at FROM rooms WHERE is_private = FALSE ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPublicRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicRooms(ctx context.Context, arg ListPublicRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listPublicRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Tags,
			&i.IsPrivate,
			&i.OwnerID,
			&i.AnonymousSessionID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByOwner = `-- name: ListRoomsByOwner :many
SELECT id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at FROM rooms WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRoomsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Tags,
			&i.IsPrivate,
			&i.OwnerID,
			&i.AnonymousSessionID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET display_name = $2, description = $3, tags = $4, last_active_at = NOW()
WHERE id = $1
RETURNING id, slug, display_name, description, tags, is_private, owner_id, anonymous_session_id, token_hash, created_at, last_active_at, expires_at
`

type UpdateRoomParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Tags,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Tags,
		&i.IsPrivate,
		&i.OwnerID,
		&i.AnonymousSessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateRoomActivity = `-- name: UpdateRoomActivity :exec
UPDATE rooms SET last_active_at = NOW(), expires_at = NOW() + INTERVAL '3 days'
WHERE id = $1 AND expires_at IS NOT NULL
`

func (q *Queries) UpdateRoomActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateRoomActivity, id)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, display_name, avatar_url, provider, provider_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_id)
DO UPDATE SET display_name = EXCLUDED.display_name, avatar_url = EXCLUDED.avatar_url, updated_at = NOW()
RETURNING id, email, display_name, avatar_url, provider, provider_id, created_at, updated_at
`

type UpsertUserParams struct {
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (room_id, agent_name, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, agent_name, content, created_at
`

type InsertMessageParams struct {
	RoomID    pgtype.UUID `json:"room_id"`
	AgentName string      `json:"agent_name"`
	Content   string      `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.RoomID, arg.AgentName, arg.Content)
	var i Message
	err := row.Scan(&i.ID, &i.RoomID, &i.AgentName, &i.Content, &i.CreatedAt)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, room_id, agent_name, content, created_at
FROM messages
WHERE room_id = $1
ORDER BY id ASC
LIMIT 100
`

func (q *Queries) ListMessages(ctx context.Context, roomID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.RoomID, &i.AgentName, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listMessagesSince = `-- name: ListMessagesSince :many
SELECT id, room_id, agent_name, content, created_at
FROM messages
WHERE room_id = $1 AND id > $2
ORDER BY id ASC
LIMIT 100
`

type ListMessagesSinceParams struct {
	RoomID  pgtype.UUID `json:"room_id"`
	AfterID int64       `json:"after_id"`
}

func (q *Queries) ListMessagesSince(ctx context.Context, arg ListMessagesSinceParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesSince, arg.RoomID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.RoomID, &i.AgentName, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
