// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimAnonymousRooms(ctx context.Context, arg ClaimAnonymousRoomsParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredRooms(ctx context.Context) error
	DeleteRoom(ctx context.Context, id pgtype.UUID) error
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomBySlug(ctx context.Context, slug string) (Room, error)
	GetRoomByTokenHash(ctx context.Context, tokenHash string) (Room, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListPublicRooms(ctx context.Context, arg ListPublicRoomsParams) ([]Room, error)
	ListRoomsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Room, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateRoomActivity(ctx context.Context, id pgtype.UUID) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
